name: "[18.Testing] Docker images test"

on: workflow_dispatch

jobs:
  _18-testing-build-and-test-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Print info
        run: echo "Run _18-testing-build-and-test-docker-image"

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build docker image
        run: |
          cd docker-homework-1-app
          docker build -t get_time_app .

      - name: Run docker image
        run: |
          docker run -d --name get_time_app -p 2222:2222 get_time_app

      - name: Check docker logs
        run: |
          docker logs get_time_app
  
      - name: Test docker application
        run: |
          curl http://localhost:2222/time
          curl http://localhost:2222/time?tz=America/New_York

      - name: Check if image has not root access inside
        run: |
          date
          echo "TODO"
